import {
  ArrowLeftRight,
  BookOpen,
  Braces,
  Cake,
  Calculator,
  CalendarRange,
  CaseSensitive,
  Clock,
  Dices,
  Divide,
  Eraser,
  FileCheck,
  FileText,
  Fingerprint,
  Flame,
  Footprints,
  Globe,
  GraduationCap,
  HandCoins,
  HeartPulse,
  ImageDown,
  KeyRound,
  Landmark,
  Palette,
  Percent,
  PiggyBank,
  Pilcrow,
  QrCode,
  Ruler,
  Scale,
  Scaling,
  School,
  Sigma,
  Tag,
  Thermometer,
  TrendingUp,
  Type,
  Undo2,
  Wallet,
  Weight,
  Wrench,
  type LucideIcon,
  type LucideProps,
} from "lucide-react";
import type { IconName } from "@/types";

const icons: Record<IconName, LucideIcon> = {
  cake: Cake,
  percent: Percent,
  "graduation-cap": GraduationCap,
  school: School,
  "heart-pulse": HeartPulse,
  landmark: Landmark,
  wallet: Wallet,
  tag: Tag,
  "hand-coins": HandCoins,
  "piggy-bank": PiggyBank,
  "trending-up": TrendingUp,
  sigma: Sigma,
  scale: Scale,
  divide: Divide,
  "calendar-range": CalendarRange,
  clock: Clock,
  flame: Flame,
  footprints: Footprints,
  "qr-code": QrCode,
  "file-text": FileText,
  type: Type,
  "case-sensitive": CaseSensitive,
  "key-round": KeyRound,
  "arrow-left-right": ArrowLeftRight,
  ruler: Ruler,
  weight: Weight,
  thermometer: Thermometer,
  globe: Globe,
  scaling: Scaling,
  "image-down": ImageDown,
  braces: Braces,
  "file-check": FileCheck,
  fingerprint: Fingerprint,
  pilcrow: Pilcrow,
  dices: Dices,
  palette: Palette,
  "undo-2": Undo2,
  eraser: Eraser,
  calculator: Calculator,
  wrench: Wrench,
  "book-open": BookOpen,
};

export function Icon({ name, ...props }: { name: IconName } & LucideProps) {
  const Component = icons[name];
  return <Component aria-hidden="true" {...props} />;
}
